### ISSUE TITLE
Add pzbcm

### ISSUE THREAD

**Issue by taichi-ishitani** [aolofsson/awesome-opensource-hardware-repos#5]
Hi @aolofsson ,

We've released our collection of basic common RLT module named PZBCM.
https://github.com/pezy-computing/pzbcm

I'd like to add it to your list. Which category should I use?

**Comment by aolofsson** [comment]
Awesome! Added.

**Comment by taichi-ishitani** [comment]
Hi @aolofsson ,

Thank you for adding our project to your list.
However spelling is wrong. To fix spelling I created a PR #7.
